PORT = 4000
ALLOWED_HOSTS = "http://localhost:4000,http://localhost:8080"
LOG_LEVEL = "info"
SWAGGER = true

[MYSQL]
    URL = ""
    USER = ""
    PASSWORD = ""
    DATABASE = ""

[AUTH]
    PASSWORD = ""
    SECRET = ""
